nextauthjs/adapters

.github/workflows/canary.yml, .github/workflows/main.yml, packages/prisma/README.md, packages/prisma/prisma/migrations/20210201153732_init/migration.sql, packages/prisma/prisma/schema.prisma, packages/prisma/src/index.ts, packages/prisma/tests/index.test.ts, packages/prisma/tsconfig.json
* fix: remove ashlovell
* test: typeorm on canary
=> fix(prisma): remove rejectOnNotFound

packages/prisma/src/index.ts
- added ESLint+Prettier
- formatted Prisma source code and tests
- actually using errors from `next-auth/errors`
=> refactor(prisma): format code

packages/prisma/src/index.ts, packages/prisma/tsconfig.json, tsconfig.json
https://github.com/nextauthjs/next-auth/pull/1871
=> feat(prisma): hand over error-handling to core

.github/workflows/canary.yml, .github/workflows/main.yml, packages/prisma/src/index.ts
Will only run adapter tests for changed adapters.
Fixes #91
=> chore: only run tests for changed adapters

README.md
This PR fixes the title from "Adapterse" to "Adapters".
=> docs(readme): fix title

packages/dynamodb/README.md
This PR makes the following changes:
- fixes grammar in various places
- adds overview, contributing and license sections
- moves config to a getting started section, to keep things consistent
One early commit isn't in the format followed in the repo - sorry about that! I hope it's fine.
Single table design is ❤️!
=> docs(dynamodb): readme improvements for dynamodb

packages/dynamodb/README.md, packages/fauna/README.md, packages/firebase/README.md, packages/prisma/README.md, packages/typeorm-legacy/README.md
Added the new firebase "options" text from the next-auth/www PR (https://github.com/nextauthjs/next-auth/pull/2076) to the README here.
Also updated the badges in the header (bundlephobia and version nr.) to `canary`.
**EDIT**: Updated all packages README header badges to `canary`.
- ~[ ] Tests~
=> docs(adapters): update firebase options section + header badges

README.md, packages/prisma-legacy/README.md
Added additional links to the new `prisma-legacy` docs page.
Docs PR: https://github.com/nextauthjs/next-auth/pull/2097
- ~[ ] Tests~
#115
#116
=> docs(adapters): clarify legacy adapters more thoroughly

packages/dynamodb/README.md, packages/fauna/README.md, packages/firebase/README.md, packages/prisma-legacy/README.md, packages/prisma/README.md, packages/typeorm-legacy/README.md
Specify the `canary` branch in all install instructions.
Matching `nextauthjs/next-auth` docs PR: https://github.com/nextauthjs/next-auth/pull/2119
- ~[ ] Tests~
=> docs(all): specify canary branch in all install instructions

.github/workflows/release.yml, packages/dynamodb/CHANGELOG.md, packages/fauna/CHANGELOG.md, packages/firebase/CHANGELOG.md, packages/pouchdb/CHANGELOG.md, packages/prisma-legacy/CHANGELOG.md, packages/prisma/CHANGELOG.md, packages/typeorm-legacy/CHANGELOG.md
Test whether setting `git config` values works
=> chore: test release.yml git config

packages/prisma/README.md
broken image link on https://github.com/nextauthjs/adapters/blob/main/packages/prisma/README.md
=> docs: fix broken image link

.github/workflows/release.yml, packages/fauna/package.json, packages/fauna/src/index.js, packages/fauna/tests/index.test.ts
The built `/dist/index.js` wasn't included in the npm published package..
=> fix(fauna): include `/dist` files in published build

.github/workflows/release.yml, lerna.json, packages/dynamodb/CHANGELOG.md, packages/fauna/CHANGELOG.md, packages/firebase/CHANGELOG.md, packages/pouchdb/CHANGELOG.md, packages/prisma-legacy/CHANGELOG.md, packages/prisma/CHANGELOG.md, packages/typeorm-legacy/CHANGELOG.md
=> chore(ci): customize publish commit  message

.babelrc.js, packages/fauna/package.json
`next.js` minimum node version is now also 12.0+
=> feat(*): bump Node version to 12

.github/workflows/release.yml, packages/dynamodb/README.md, packages/fauna/README.md, packages/firebase/README.md, packages/pouchdb/README.md, packages/prisma/README.md, packages/typeorm-legacy/README.md
Dummy changes to force publishes from latest `main` code to npm.
=> chore(ci): force publish

packages/typeorm-legacy/README.md
Update links and references, etc. for adapters@next / next-auth@beta
Update the `typeorm-legacy` readme with new links, references, updated badges, etc. for the adapters@next and next-auth@beta packages, etc.
- ~[ ] Tests~
=> docs(typeorm): update `README.md`

packages/fauna/README.md
Update links / badges / example code for adapters@next / next-auth@beta.
Update the faunadb readme with new links, references, updated badges, etc. for the adapters@next and next-auth@beta packages, etc.
- ~[ ] Tests~
=> docs(fauna): update `README.md`

packages/fauna/README.md
Reverts nextauthjs/adapters#244
=> Revert "docs(fauna): update `README.md`"

packages/mongodb/README.md
In line with next-auth@beta and adapters@next changes
- ~[ ] Tests~
=> docs(mongodb): update `README.md`

packages/prisma/README.md
In line with next-auth@beta and adapters@next changes
Update the prisma readme with new links, references, updated badges, etc. for the adapters@next and next-auth@beta packages, etc.
Branch is wrong name.. also getting late for me :joy: :facepalm: at least its against the right branch this time haha.
- ~[ ] Tests~
=> docs(prisma): update `README.md`

packages/typeorm-legacy/package.json, packages/typeorm-legacy/tests/mysql/index.custom.test.ts, packages/typeorm-legacy/tests/sqlite/index.test.ts, yarn.lock
Related https://github.com/nextauthjs/adapters/discussions/306, https://github.com/nextauthjs/docs/pull/112
=> test(typeorm): run naming strategy test

packages/neo4j/tests/index.test.ts, packages/neo4j/tests/resources/statements.ts, packages/neo4j/tests/test.sh
.cypher file was causing issues in some local and the CI environment. These database initialising statements for creating indexes and contstrains for tests are now applied at the start of the tests using ts, rather than before using bash.
Comment https://github.com/nextauthjs/adapters/pull/314#issuecomment-974631632
=> chore(neo4j): Test refactor constraints

packages/neo4j/src/index.ts, packages/neo4j/src/utils.ts, packages/neo4j/tests/index.test.ts
After a read through @balazsorban44 's refactor I made a few minor amends. Thanks btw, I leadned a lot!
- Add to tests to fail if userId foreign key exists on session or account.
- CreateSession, don't add userId on Session node
- For the above change to CreateSession, amend format.to to allow nested objects
- On create statements, = can be uses instead of +=
Following on from PR https://github.com/nextauthjs/adapters/pull/314
=> chore(neo4j): minor amend to tests

packages/dynamodb/src/index.ts, packages/dynamodb/src/utils.ts, packages/dynamodb/tests/index.test.ts
Some last-minute cleanup of the source-code @mathisobadia, hope you don't mind. It's mostly simplified to match the style of the other adapters as well.
=> refactor(dynamo): clean up

packages/sequelize/README.md
There was a type in an installation command.
=> docs(sequelize): fix typo in `README.md`

packages/fauna/src/index.ts
Changes to fix #364 on the fauna adapter.
- ~[ ] Documentation~
Fixes #364
=> Convert value prop to Date only if of type string

.github/workflows/release.yml, packages/upstash-redis/src/index.ts
=> fix(upstash-redis): expose environment variables in workflow

packages/fauna/src/index.ts, packages/firebase/src/index.ts, packages/pouchdb/src/index.ts, packages/sequelize/src/index.ts, packages/typeorm-legacy/src/entities.ts, packages/typeorm-legacy/src/index.ts, packages/typeorm-legacy/src/utils.ts, packages/typeorm-legacy/tests/custom-entities.ts, packages/typeorm-legacy/tests/helpers.ts
Fix the `eslint` errors and warning so that I can be able to commit without being blocked by `husky`.
All the warnings with imports are fixed automatically with `--fix` flag, I fix the 2 errors by casting `secret` to string.
- ~~[ ] Documentation~~
- ~~[ ] Tests~~
None
=> chore: fix eslint errors & warnings

README.md
Added warning in README that all adapter code has been migrated to our new monorepo.
=> chore: add deprecation warning to README.md
